# Generated by Django 3.2.3 on 2021-05-17 11:15

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
